Module_1 Lab | Statistical Computing | BANA 6043

Question 1: BMI
Given the equation for calculating Body Mass Index (BMI) is:
Say an individual weighs 150 lbs and is 68 inches tall. What is their BMI?
𝐵𝑀𝐼 =
weight in pounds × 703
height in inches2
wt
=
___
ht
=
___
bmi
=
______

In [32]:
wt = 150
ht = 68

bmi = (wt * 703)/ ht**2
bmi
# 22.80493079584775
round(bmi,1)



22.8

Question 2: Math Library
1.Import the math library.
2.Find a function within the math library that will compute the square root of 14 × 0.51
3.Find a function with the math library that will compute 3.25 ^ 2.784
Now compute this with a simple math operator provided by standard Python.


In [33]:
# 1.
import math

# 2.
a = 14 * 0.51
b = math.sqrt(a)
print(round(b,2))
# 2.6720778431774774



# 3.
import random

c =  3.25 ** 2.784
c
#d = round(26.61235308864194,4)
#d


2.67


26.61235308864194

Question 3: Cost of Pizza
Say you have a 12” diameter pizza. And given the area of a circle is , compute the area of
the pizza and assign that value to the variable area . Now say the cost of the pizza was $8. Compute the cost
per square inch of this pizza. **Hint**: the `math` library contains a `pi` object to use as .
𝐴 = 𝜋(diameter/2)2
𝜋
Now say you have the option to buy the above pizza or a 15" pizza that costs $12. Which is a better deal?

In [34]:
import math as M
pizza = 12
area = math.pi * ((pizza/2)**2)
area
area_1 =8/area
print("Pizza that costs $8" ,area_1)


2.
pizza_1 = 15
area_2 = math.pi * ((pizza_1/2)**2)
area_2
area_3 =12/area_2
print("Pizza that costs $12", area_3)

Pizza that costs $8 0.0707355302630646
Pizza that costs $12 0.06790610905254202


Question 4: Conditional Statements and Snakes
Given the variable language which contains a string, use if/elif/else to write a program that:
returns “I love snakes!” if language is "python" (any kind of capitalization)
returns “Are you a pirate?” if language is "R" (any kind of capitalization)
returns “What is language?” if language is anything else.

In [35]:
language = "python"

if language == "python":
    print("I love snakes!")
elif language =="R":
    print("Are you a pirate?")
else:
    print("What is language?")


language = "R"

if language == "python":
    print("I love snakes!")
elif language =="R":
    print("Are you a pirate?")
else:
    print("What is language?")


language = "xyz"

if language == "python":
    print("I love snakes!")
elif language =="R":
    print("Are you a pirate?")
else:
    print("What is language?")

I love snakes!
Are you a pirate?
What is language?


Question 5: Analyzing a Vector of Weights
1. Create a list called weight containing the weight (in kg) of 10 children: 69, 62, 57, 59, 59, 64, 56, 66, 67, 66.
2. Try and convert these weights to pounds using (1kg = 2.20462lbs). If you try weight * 2.20462 what
results?
3. Import the numpy library and use the alias np .
4. Now convert weight to an array with np.array() .
5. Now try and convert the array of weights to pounds using weight * 2.20462 what results?
6. Use numpy functions to compute the mean and standard deviation of the weights in pounds.
7. How many children weigh more than the average?

In [36]:
import numpy as np
weight = [69, 62, 57, 59, 59, 64, 56, 66, 67, 66]
print(weight)
# Converting weights to Pounds
new_weight = []
for weights in weight:
    new_weight.append(weights* 2.20462)
print(new_weight)

type(new_weight)

import numpy as np


conv_new_weight = np.array(weight)
conv_new_weight

an_array = np.array(conv_new_weight)
conv_new_weight_1 = an_array *2.20462
conv_new_weight_1

# Mean and Standard deviation of weights in Pounds

mean_weight_1 = np.mean(new_weight)
print(mean_weight_1)

std_dev_1 = np.std(new_weight)
print(std_dev_1)

# Average and Children weigh more than the average
average_weight_1 = np.average(weight)
print(average_weight_1)

count = len([elem for elem in new_weight if elem > mean_weight_1])
print('Children weigh more than the average are ', count)
    

[69, 62, 57, 59, 59, 64, 56, 66, 67, 66]
[152.11878, 136.68643999999998, 125.66333999999999, 130.07258, 130.07258, 141.09568, 123.45871999999999, 145.50492, 147.70953999999998, 145.50492]
137.78875
9.520793836285922
62.5
Children weigh more than the average are  5


Question 6: Back to BMI
Say we have the following height (in inches) for our 10 children: 62, 58, 61, 61, 59, 64, 63, 61, 60, 62. Use the
weights from the last execise and these height values to compute the BMI for each child. What is the average
BMI across all the children?

In [37]:
import numpy as np
height = [62, 58, 61, 61, 59, 64, 63, 61, 60, 62]
new_weight = [152.11878, 136.68643999999998, 125.66333999999999, 130.07258, 130.07258, 141.09568, 123.45871999999999, 145.50492, 147.70953999999998, 145.50492]
new_height= [number ** 2 for number in height]
new_height

new_weight_11 = [number * 703 for number in new_weight]
new_weight_11

BMI = [i/j for i,j in zip(new_weight_11,new_height)]
print(BMI)

new_BMI_1 = np.mean(BMI)
print(new_BMI_1)



[27.819849724245575, 28.564377919143872, 23.74128675624832, 24.574314361730714, 26.268607796610166, 24.216372812499998, 21.86734194003527, 27.489910980919106, 28.844390727777775, 26.610291040582723]
25.999674405979352


Question 7: Nested Dictionary
Given this nest dictionary, extract the element containing the word “BANA”
In [1]: d = {
"a_list": [1, 2, 3,],
"a_dict": {"first": ["this", "is", "inception"],
"second": [1, 2, 3, "BANA"]}
}

In [38]:
d = {
"a_list": [1, 2, 3,],
"a_dict": {"first": ["this", "is", "inception"],
"second": [1, 2, 3, "BANA"]}
}
d

one = d['a_dict']['second'][3]
print(one)

two = d["a_dict"]["second"][-1]
print(two)

BANA
BANA


Question 8: Sorting Arrays
Lets create 20 random integers where the values are randomly created from the value range of 50-100. We'll say
these random integers represent the weight of 20 children. We'll use numpy to generate these numbers. Be
sure to use seed(123) so we get the same results.

In [2]: # random generating functions
from numpy.random import seed
from numpy.random import randint
# seed random number generator
seed(123)
# generate 20 random numbers between 50-100
weights = randint(low=50, high=100, size=20)

Identify the weights of the three children that have the lightest weight values. Hint: figure out how to sort these
values in ascending order and index the first three values.

In [39]:
import numpy as np
from numpy.random import seed
from numpy.random import randint
# seed random number generator
seed(123)
# generate 20 random numbers between 50-100
weights = randint(low=50, high=100, size=20)
print(weights)

sorted_array_new = np.sort(weights)
print(sorted_array_new)
sorted_array_new[0:3]



[95 52 78 84 88 67 69 92 72 83 82 99 97 59 82 96 82 97 75 69]
[52 59 67 69 69 72 75 78 82 82 82 83 84 88 92 95 96 97 97 99]


array([52, 59, 67])

Question 9: The Zen of Python

Run the following code. Read and embrace this mantra throughout this class and your Python code-writing
lives!
import this

In [43]:
import this

# Adding the o/p as markdown because I wasn't able to run this again and agin.
>>> import this
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!